In [5]:
import numpy as np
x=np.array([1,2,3,4])
Ordinary_list = x.tolist()

print (Ordinary_list)

[1, 2, 3, 4]


In [8]:
import numpy as np
a = []
for i in range (3):
    b = []
    for j in range (3):
        j = int(input("Enter number in the bracket ["+str(i)+"]["+str(j)+"]"))
        b.append(j)
    a.append(b)
print ("Your Matrix is  ")
for i in range (3):
    for j in range (3):
        print (a[i][j],end = " ")
    print()
m = np.array(a)
print (np.trace(m))

Enter number in the bracket [0][0]10
Enter number in the bracket [0][1]25
Enter number in the bracket [0][2]20
Enter number in the bracket [1][0]6
Enter number in the bracket [1][1]8
Enter number in the bracket [1][2]95
Enter number in the bracket [2][0]56
Enter number in the bracket [2][1]56
Enter number in the bracket [2][2]66
Your Matrix is  
10 25 20 
6 8 95 
56 56 66 
84


In [9]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
x=2
for i in a:
    b = (a[:,-1] > x)
print (b)    

[False  True  True]


In [13]:
import numpy as np
A=np.array([[1,5],[5,1]], dtype=np.float64)
B=np.array([[7,0],[9,5]], dtype=np.float64)
C=np.add(A, B)
C=A+B
print (C)

[[ 8.  5.]
 [14.  6.]]


In [17]:
import numpy as np
array=np.random.randint(2, 10, size=(3,5))

print(np.mean(array))

6.733333333333333


In [19]:
print(array - array.mean(axis=1, keepdims=True) )

[[-0.6  1.4  1.4 -3.6  1.4]
 [ 0.4  1.4 -3.6 -0.6  2.4]
 [ 1.   0.  -3.  -1.   3. ]]
